name: CI/CD

on:
  push:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  API_IMAGE: bsalamea/aiberry-api

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.API_IMAGE }}:${{ steps.vars.outputs.sha_short }}

  cd:
    needs: ci
    runs-on: self-hosted  # Must have kubectl + argocd CLI
    steps:
      - name: Checkout deployments
        uses: actions/checkout@v4
        with:
          repository: salamea/aiberrydeployments
          path: deployments

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update dev values
        working-directory: deployments
        run: |
          yq -i '.image.tag = "${{ needs.ci.outputs.sha_short }}"' environments/dev/aiberry-api-values.yaml

      - name: Commit and push changes
        uses: Endbug/add-and-commit@v9
        with:
          cwd: deployments
          message: "ci: update image tags to ${{ needs.ci.outputs.sha_short }}"
          push: true

      - name: Sync ArgoCD
        run: |
          argocd login argocd-server.argocd --insecure --grpc-web \
            --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync aiberry-dev